FROM python:3.9-slim-buster

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY websocket_server.py .

EXPOSE 8001 8002

CMD ["python", "websocket_server.py"]